name: Pac-Man Contribution Graph

on:
  push: {}
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pac-Man Graph
        uses: Platane/pacman-contribution-graph@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg?theme=dark&color_dots=#161b22,#006d32,#26a641,#39d353,#ebedf0

      - name: Push Pac-Man files
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
